### PR TITLE
Exercise 2

### PR DESCRIPTION
**Pull request by Xnasav**
Implemented some test cases and left out travis ci for now - working on that later. Handing in pull request due to todays deadline. Will improve test cases and code quality @roschaefer

### CODE REVIEW

**Comment by roschaefer** [comment]
@Xnasav 
Screenshot - 2019-11-17T233525 536

**Comment by Xnasav** [comment]
@roschaefer There is no such option for me - what am I missing

image

**Comment by m-oehme** [comment]
@Xnasav 
you are trying to merge into @roschaefer  upstream repo
Re-Create your PR and change the repos you want to merge into. (default it selects Roberts repo but you need to select yours!)
The PR #21 had the same issue. There are some pictures in the comments.

Also, you don't have a build-server yet. Don't forget about it ;)

**Comment by roschaefer** [comment]
Oh yes @m-oehme is totally right! Of course I can make myself a reviewer in my own repo. @Xnasav you need to create the PR in your own fork.

Closing..

**Pull request closed without merging**
