### PR TITLE
Code Review exercise 2

### PR DESCRIPTION
**Pull request by Chuvantinh**
Dear Mr. Robert

we are a group in SDF with 3 peoples
@michaelef123 | Michael Franz
@Chuvantinh | Chu Văn Tình
@itfak | Arnauld Feussi

We had done the exercise 2 from last week, because the permission on github.com, I can't invite you to review code.

 but today I have pushed code to you again. I hope you can see the code and have some comments to us. Thanks

Yours sincerely
Chu

### CODE REVIEW

**Comment by m-oehme** [comment]
You're trying to merge your Repository into his. That will not work. (in this case)

You have to merge from one of your branches where you did Exercise 2 into the master branch, within you own repository.

When creating a pull request GitHub will automatically select to merge from your repo into Roberts repo since its a fork. It looks like this:
Bildschirmfoto 2019-11-17 um 17 24 35
On the top line change the "base repository" in the dropdown list to your own repo. Than it will change to this:
Bildschirmfoto 2019-11-17 um 17 24 58
Like I said this is when you try to create a pull request.

**Comment by Chuvantinh** [comment]
@roschaefer 
I can not add you as a reviewer, therefore  I would like to comment here.
thanks

**Comment by m-oehme** [comment]
@Chuvantinh 
pls look at my comment above.
You cannot add @roschaefer as a reviewer if you are trying to do a pull request with HIS repository.
you have to do it within your own repo.

**Comment by roschaefer** [comment]
@m-oehme @Chuvantinh excellent! You're helping each other out :heart: that's what I mean when I make "Learn and Share" the motto of our course.

@Chuvantinh I know that you had troubles to communicate with the owner of your fork. He did not give you admin permissions so you couldn't setup Travis CI and you couldn't add others as collaborators (thus you couldn't request code reviews from other people).

Now when I enter https://github.com/michaelef123/Systems-Development-and-Frameworks I get redirected to https://github.com/Chuvantinh/Systems-Development-and-Frameworks. To me this looks like you transferred ownership. Is that correct?

In any case @m-oehme is correct when he suggests that you can create a PR from a source branch of your own repository into a target branch of your own repository. This PR here has a target branch in `roschaefer/Systems-Development-and-Frameworks` but it the PR should point at `Chuvantinh/Systems-Development-and-Frameworks`.

@m-oehme shows a screenshot indicating how you can create a PR within your own fork of the repo.

Of course, if you have troubles, I can also review this PR. But it's good practice to merge the PR after an approval. And I cannot merge this PR into my repo.

**Comment by roschaefer** [comment]
Screenshot - 2019-11-17T235200 854

For explanation

**Comment by Chuvantinh** [comment]
Thank @roschaefer  and @m-oehme 
Oki the destination should stay in our repository.

I do like you tell me. But in fact, I can't add you as a reviewer, I think because you didn't confirm our invitation. @roschaefer  Can you check again the invitation in your Gmail or E-mail?

I have tried to create a new GitHub account to test this thing (that is "vantinhchu-roboter"). And then I can add this account as the reviewer. I have posted 2 photos pls see it

Screenshot 2019-11-18 at 17 05 45

Screenshot 2019-11-18 at 17 15 28

- more one thing: Michael transferred this repository to me like admin. in the past I deleted my branch and now I have created a new branch "exercise_2".

**Comment by roschaefer** [comment]
@Chuvantinh yes, absolutely right! So I'm going to close this PR because you know now what to do in order to create the PR in your fork.

@Chuvantinh here is what I see when I go to https://github.com/Chuvantinh/Systems-Development-and-Frameworks/invitations and click on "Accept invitation"

Screenshot - 2019-11-19T001141 542


Could you resend the invitation, please?

**Pull request closed without merging**
